### ISSUE TITLE
Differenct sentimental score on same sentence

### ISSUE THREAD

**Issue by jmhwang-dev** [jmhwang-dev/e-commerce#30]
```yaml
src_path: null
dst_path: ./artifact/inference/check_gpu2.csv
inplace: true
checkpoint: j-hartmann/sentiment-roberta-large-english-3-classes
device: cuda
initial_batch_size: 300
```

Input: [trans-p2e.txt](https://github.com/user-attachments/files/20663918/trans-p2e.txt)

Sentence: I would recommend it.

| Score Set | Negative           | Neutral            | Positive           |
| --------- | ------------------ | ------------------ | ------------------ |
| Score1    | 0.0001627616438781 | 0.0002063312131213 | 0.9996309280395508 |
| Score2    | 0.000780064438004  | 0.9980935454368592 | 0.0011263494379818 |
