### ISSUE TITLE
Strange translation

### ISSUE THREAD

**Issue by jmhwang-dev** [jmhwang-dev/e-commerce#8]
# 26486 sentence

## configuration
From Portuguese into English
```yml
src_path: ./artifact/preprocess/all_portuguess.txt
dst_path: ./artifact/inference/trans_p2e_auto.txt
inplace: true
checkpoint: Unbabel/TowerInstruct-7B-v0.2
device: auto
initial_batch_size: 10
language_from: Portuguese
language_into: English
```
From English into Korean
```yml
src_path: ./artifact/inference/trans_p2e.txt
dst_path: ./artifact/inference/trans_e2k_cpu_3591.txt
inplace: true
checkpoint: Unbabel/TowerInstruct-7B-v0.2
device: cpu
initial_batch_size: 1
language_from: English
language_into: Korean
```
## result
![Image](https://github.com/user-attachments/assets/ef8c3cc9-ee94-499c-ba51-10534075d83b)
```
Portuguess:
guarda chuva veio com pequenos furos

English:
um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um um

Korean:
예를 들어 보겠습니다. 예제 1: 숫자 1을 숫자 10으로 변환하는 방법은 무엇입니까? 예제 2: 숫자 10을 숫자 1으로 변환하는 방법은 무엇입니까? 숫자 1을 숫자 10으로 변환하는 방법은 다음과 같습니다. 1을 1로 나누고 1을 10으로 나눕니다. 즉, 1을 10으로 나눈는 것입니다. 숫자 10을 숫자 1으로 변환하는 방법은 다음과 같습니다. 10을 1으로 나누고 10을 1으로 나눕니다. 즉, 10을 1으로 나눈는 것입니다. 즉, 1을 10으로 나눈는 것입니다.
```

# 30554 sentence

```yml
src_path: null
dst_path: ./artifact/inference/trans_e2k_cpu_3591_2.txt
inplace: true
checkpoint: Unbabel/TowerInstruct-7B-v0.2
device: cpu
initial_batch_size: 10
language_from: English
language_into: Korean

```

```
Portuguess:
faltou 02 tubos de bolinas

English:
02 tubes of wool were missing

Korean:
02 왁스 왁스 왁스 왁스 왁스 왁스 왁스 왁스 왁스 왁스 왁스 왁스 왁스 왁스 왁스 왁스 왁스 왁스 왁스 왁스 왁스 왁스 왁스 왁스 왁스 왁스 왁스 왁스 왁스 왁스 왁스 왁스 왁스 왁스 왁스 왁스 왁스 왁스 왁스 왁스 왁스 왁스 왁스 왁스 왁스 왁스 왁스 왁스 왁스 왁스 왁스 왁스 왁스 왁스 왁스 왁스 왁스 왁스 왁스 왁스 왁스 왁스 왁스 왁스 왁스 왁스 왁스 왁스 왁스 왁스 왁스 왁스 왁스 왁스 왁스 왁스 왁스 왁스 왁스 왁스 왁스 왁스 왁스 왁스 왁스 왁스 왁스 왁스 왁스 왁스 왁스 왁스 왁스 왁스 왁스 왁스 왁스 왁스 왁스 왁스 왁스 왁
```
